### ISSUE TITLE
啥时候支持下正方形啊

### ISSUE THREAD

**Issue by pcarm** [Modificator/water-wave-progress#6]
啥时候支持下正方形啊

**Comment by Modificator** [comment]
啥意思

**Comment by pcarm** [comment]
> 
> 
> 啥意思

就是这个view现在不是圆的嘛，， 没有能设置成方形的属性啊

**Comment by Modificator** [comment]
咦，一直以为有正方形来着
这一行去掉就是正方形了
https://github.com/Modificator/water-wave-progress/blob/72ed3f418004603240cfd84916a1aef05d2f7a84/WaterWaveProgress/src/main/java/cn/modificator/waterwave_progress/WaterWaveProgress.java#L243

**Comment by pcarm** [comment]
> 
> 
> 咦，一直以为有正方形来着
> 这一行去掉就是正方形了
> 
> https://github.com/Modificator/water-wave-progress/blob/72ed3f418004603240cfd84916a1aef05d2f7a84/WaterWaveProgress/src/main/java/cn/modificator/waterwave_progress/WaterWaveProgress.java#L243
哦了~ 谢了~
